Fix or comment out bad assembly code that gcc 5.2 rejects with the error
```
Error: incorrect register `%rax' used with `w' suffix
```

This only appears when make is run with ``SYNTAX_ONLY=0`` because
when gcc is passed ``-fsyntax-only`` (i.e. ``SYNTAX_ONLY=1``) the
GNU assembler is not invoked.

This fixes issue #42